export { default as CIcon } from './Icon';
export { default as CText } from './Text';
export { default as CHtml } from './Html';
export { default as CLink } from './Link';
export { default as CList } from './List';
export { default as CButton } from './Button';
export { default as CImage } from './Image';
export { default as CHeading } from './Heading';
export { default as CFaq } from './Faq';